apiVersion: v1
data:
  config.yml: |
    tunnel: cb2a7768-4162-4da9-ac04-138fdecf3e3d
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: mirai.sogos.io
        service: http://mirai-frontend.default.svc.cluster.local:80
      - hostname: argocd.sogos.io
        service: http://argocd-server.argocd.svc.cluster.local:80
      - hostname: grafana.sogos.io
        service: http://grafana.monitoring.svc.cluster.local:3000
      - hostname: hello.sogos.io
        service: http://hello-world.default.svc.cluster.local:80
      - hostname: solutions.sogos.io
        service: http://solutions.default.svc.cluster.local:80
      - hostname: product.sogos.io
        service: http://product.default.svc.cluster.local:80
      - service: http_status:404
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yml":"tunnel: cb2a7768-4162-4da9-ac04-138fdecf3e3d\ncredentials-file: /etc/cloudflared/credentials.json\ningress:\n  - hostname: mirai.sogos.io\n    service: http://mirai-frontend.default.svc.cluster.local:80\n  - hostname: argocd.sogos.io\n    service: http://argocd-server.argocd.svc.cluster.local:80\n  - hostname: grafana.sogos.io\n    service: http://grafana.monitoring.svc.cluster.local:3000\n  - hostname: hello.sogos.io\n    service: http://hello-world.default.svc.cluster.local:80\n  - hostname: solutions.sogos.io\n    service: http://solutions.default.svc.cluster.local:80\n  - hostname: product.sogos.io\n    service: http://product.default.svc.cluster.local:80\n  - service: http_status:404\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"cloudflared-config","namespace":"default"}}
  creationTimestamp: "2025-10-16T18:36:59Z"
  name: cloudflared-config
  namespace: default
  resourceVersion: "5092917"
  uid: 9a8578a4-1b33-4fbd-8cdf-36efe9621085
