apiVersion: v1
kind: Service
metadata:
  name: wireguard-failover
  namespace: ingress
  labels:
    app: wireguard-failover
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: wireguard-failover
